#!/bin/bash
SCRPATH=$(cd ${0%/*} && echo $PWD/${0##*/})
CPATH=`dirname "$SCRPATH"`
BASEX=$1

if [ $# -eq 2 ];
then
        echo "BatMeth2 RRBS build index " $2
        if [ "$1" == "rrbs" ];
        then
		BASEX=$2
                $CPATH/build_index_rrbs $BASEX
                mv $BASEX ${BASEX}.original.fa
                mv ${BASEX}.rrbs.fa ${BASEX}
        fi
fi

if [ -n "$BASEX" ];
then
	#$CPATH/genome_filter $BASEX > ${BASEX}.format.fa
	#mv ${BASEX}.format.fa $BASEX
	$CPATH/build_indexX $BASEX CTOT
	$CPATH/build_indexX $BASEX GTOA
	rm *.bin
	$CPATH/build_indexX $BASEX
fi
